In [1]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [5]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [1]:
import numpy as np

In [2]:
list = [1, 2, 3, 4]

In [3]:
list

[1, 2, 3, 4]

In [4]:
nparray = np.array(list)

In [5]:
nparray

array([1, 2, 3, 4])

In [6]:
type(nparray)

numpy.ndarray

In [7]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(4)

array([0.71923358, 0.03959708, 0.81180898, 0.68441417])

In [20]:
randomNum = np.random.rand(1) * 100
randomNum

array([88.72474815])

In [21]:
randomNum[0]

88.72474814613457

In [22]:
np.random.rand(2, 3)

array([[0.55105133, 0.52271492, 0.48389369],
       [0.17504132, 0.2433679 , 0.35165417]])

In [27]:
np.random.randn(2, 3)

array([[ 0.28090321,  0.03998321,  0.61851147],
       [-0.24857644,  1.38151366,  1.39630873]])

In [30]:
np.random.randint(0, 101, (3, 4))

array([[33, 21, 13, 62],
       [82, 42, 79, 72],
       [75, 12, 38, 87]])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(0, 25)

In [34]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
minmax = np.random.randint(0, 30, 10)
minmax

array([ 6, 25, 18, 22, 10, 10, 23, 20,  3,  7])

In [36]:
minmax.min()

3

In [37]:
minmax.max()

25

In [38]:
minmax.argmin()

8

In [40]:
minmax.argmax()

1

In [42]:
minmax.dtype

dtype('int32')

In [51]:
arra = np.arange(0, 25)
arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arra.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arra.shape

(25,)

In [57]:
arra.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arra.shape

(25,)

In [59]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr[0:4]

array([0, 1, 2, 3])

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[0:4] = 99
arr

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_array = arr[0:4]
slice_of_array

array([0, 1, 2, 3])

In [70]:
slice_of_array[:] = 99
slice_of_array

array([99, 99, 99, 99])

In [71]:
arr

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [72]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [73]:
arr_copy[:3] = 0
arr_copy

array([ 0,  0,  0, 99,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr

array([99, 99, 99, 99,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
arr_2d.shape

(3, 3)

In [80]:
arr_2d[1][1]

25

In [85]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [86]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [88]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [91]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [92]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [93]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [94]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr.sum()

55

In [96]:
arr.std()

3.1622776601683795

In [97]:
arr.var()

10.0

In [100]:
arr_2d = np.arange(0, 25).reshape(5, 5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [101]:
arr_2d.sum(axis = 0)

array([50, 55, 60, 65, 70])

In [102]:
arr_2d.sum(axis = 1)

array([ 10,  35,  60,  85, 110])

In [1]:
import numpy as np

In [4]:
arr = [1, 2, 3, 4, 5]
arr

[1, 2, 3, 4, 5]

In [6]:
type(arr)

list

In [7]:
nparray = np.array(

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

list