In [1]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [5]:
for i in range(0, 10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [1]:
import numpy as np

In [2]:
list = [1, 2, 3, 4]

In [3]:
list

[1, 2, 3, 4]

In [4]:
nparray = np.array(list)

In [5]:
nparray

array([1, 2, 3, 4])

In [6]:
type(nparray)

numpy.ndarray

In [7]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
np.random.rand(4)

array([0.71923358, 0.03959708, 0.81180898, 0.68441417])

In [20]:
randomNum = np.random.rand(1) * 100
randomNum

array([88.72474815])

In [21]:
randomNum[0]

88.72474814613457

In [22]:
np.random.rand(2, 3)

array([[0.55105133, 0.52271492, 0.48389369],
       [0.17504132, 0.2433679 , 0.35165417]])

In [27]:
np.random.randn(2, 3)

array([[ 0.28090321,  0.03998321,  0.61851147],
       [-0.24857644,  1.38151366,  1.39630873]])

In [30]:
np.random.randint(0, 101, (3, 4))

array([[33, 21, 13, 62],
       [82, 42, 79, 72],
       [75, 12, 38, 87]])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [32]:
arr = np.arange(0, 25)

In [34]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
minmax = np.random.randint(0, 30, 10)
minmax

array([ 6, 25, 18, 22, 10, 10, 23, 20,  3,  7])

In [36]:
minmax.min()

3

In [37]:
minmax.max()

25

In [38]:
minmax.argmin()

8

In [40]:
minmax.argmax()

1

In [42]:
minmax.dtype

dtype('int32')

In [51]:
arra = np.arange(0, 25)
arra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
arra.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arra.shape

(25,)

In [55]:
arra.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
a